# Generated by Django 3.2.2 on 2021-06-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarsifyApp', '0003_address_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='PanNumber',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='VoterID',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
