# Generated by Django 3.2.2 on 2021-06-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarsifyApp', '0006_rename_profile_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='usr',
            new_name='user',
        ),
    ]
