# Generated by Django 3.2.2 on 2021-06-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarsifyApp', '0007_rename_usr_address_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='State',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.IntegerField(null=True),
        ),
    ]
