# Generated by Django 3.2.2 on 2021-06-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarsifyApp', '0008_auto_20210611_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='City',
            field=models.TextField(null=True),
        ),
    ]
