# Generated by Django 3.2.2 on 2021-06-11 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CarsifyApp', '0010_auto_20210611_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavouriteCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CarsifyApp.individual_car_details')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
