# Generated by Django 3.2.2 on 2021-06-30 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarsifyApp', '0011_userfavouritecars'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual_car_details',
            name='Car_Status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Individual_Car_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image1', models.ImageField(null=True, upload_to='')),
                ('Image2', models.ImageField(null=True, upload_to='')),
                ('Image3', models.ImageField(null=True, upload_to='')),
                ('Image4', models.ImageField(null=True, upload_to='')),
                ('Image5', models.ImageField(null=True, upload_to='')),
                ('Image6', models.ImageField(null=True, upload_to='')),
                ('Image7', models.ImageField(null=True, upload_to='')),
                ('Image8', models.ImageField(null=True, upload_to='')),
                ('Image9', models.ImageField(null=True, upload_to='')),
                ('Image10', models.ImageField(null=True, upload_to='')),
                ('carid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CarsifyApp.individual_car_details')),
            ],
        ),
    ]
