# Generated by Django 3.2.2 on 2021-07-02 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarsifyApp', '0013_number_of_owners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number_of_owners',
            name='carid',
        ),
        migrations.AddField(
            model_name='individual_car_details',
            name='Owners',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CarsifyApp.number_of_owners'),
        ),
        migrations.AlterField(
            model_name='individual_car_images',
            name='Image1',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='individual_car_images',
            name='Image10',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='individual_car_images',
            name='Image2',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='individual_car_images',
            name='Image3',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='individual_car_images',
            name='Image4',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='individual_car_images',
            name='Image5',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='individual_car_images',
            name='Image6',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='individual_car_images',
            name='Image7',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='individual_car_images',
            name='Image8',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='individual_car_images',
            name='Image9',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
