# Generated by Django 3.2.2 on 2021-07-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarsifyApp', '0014_auto_20210702_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='number_of_owners',
            name='Postfix',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
