# Generated by Django 3.2.2 on 2021-07-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarsifyApp', '0015_number_of_owners_postfix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number_of_owners',
            name='Postfix',
            field=models.TextField(null=True),
        ),
    ]
