# Generated by Django 3.2.2 on 2021-07-02 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarsifyApp', '0016_alter_number_of_owners_postfix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual_car_details',
            name='Owners',
        ),
        migrations.DeleteModel(
            name='Number_of_Owners',
        ),
    ]
