# Generated by Django 3.2.2 on 2021-07-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarsifyApp', '0017_auto_20210702_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number_of_Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owners', models.IntegerField(null=True)),
                ('Postfix', models.TextField(null=True)),
            ],
        ),
    ]
