# Generated by Django 3.2.2 on 2021-07-02 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarsifyApp', '0018_number_of_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual_car_details',
            name='Owners',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CarsifyApp.number_of_owners'),
        ),
    ]
