# Generated by Django 3.2.2 on 2021-07-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarsifyApp', '0021_individual_car_details_body_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual_car_details',
            name='City',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='individual_car_details',
            name='Discription',
            field=models.TextField(null=True),
        ),
    ]
