# Generated by Django 3.2.2 on 2021-07-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarsifyApp', '0022_auto_20210703_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual_car_details',
            name='Images',
        ),
        migrations.RemoveField(
            model_name='individual_car_images',
            name='Image1',
        ),
        migrations.RemoveField(
            model_name='individual_car_images',
            name='Image10',
        ),
        migrations.RemoveField(
            model_name='individual_car_images',
            name='Image2',
        ),
        migrations.RemoveField(
            model_name='individual_car_images',
            name='Image3',
        ),
        migrations.RemoveField(
            model_name='individual_car_images',
            name='Image4',
        ),
        migrations.RemoveField(
            model_name='individual_car_images',
            name='Image5',
        ),
        migrations.RemoveField(
            model_name='individual_car_images',
            name='Image6',
        ),
        migrations.RemoveField(
            model_name='individual_car_images',
            name='Image7',
        ),
        migrations.RemoveField(
            model_name='individual_car_images',
            name='Image8',
        ),
        migrations.RemoveField(
            model_name='individual_car_images',
            name='Image9',
        ),
        migrations.AddField(
            model_name='individual_car_images',
            name='Image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
