# Generated by Django 3.2.2 on 2021-07-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarsifyApp', '0023_auto_20210703_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual_car_details',
            name='Showimage',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
